# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CSE 5525
semester: Spring 2025
university: The Ohio State University
tagline: NLP (Spring 2025)
description: Foundations of Speech and Language Processing
author: Sachin Kumar
baseurl: '/cse-5525-spring-2025' # the subpath of your site, e.g. /blog
url: 'https://shocheen.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
logo: "/assets/images/osu-2.png"
kramdown:
  toc_levels: 1..2

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.8.2
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  "Canvas":
    - "#"
  "Teams":
    - "#"
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
